version: "1.9"

debug: false

# Addons- install the plugins to get support from menu mine!
addons:
  MenuMineStorage: true

# setting this true will be use SpigotAPI for some actions like ActionBar or Titles from 1.20 to new versions!
ignoreNew: true

defaultLanguage: 'en'
logMessages: true
Metrics: true
# Interact event used as in game menu creation system + set placeholders when someone opens the menu
# - if you don't want to use in game menu system & optimize disable this future
# - if you don't want to use placeholders disable it (it's also optimize the plugin)
InteractEvent: true
PlaceholderAPI_support: true

MenuItem: false

# When an action returns false, automatically plugin use preLoaded language messages.
# if you use the denyActions in new versions, you can disable this
AutoMessageComplete: true

# Available NBT systems:
# - spigot (for 1.14+)
# - madeIn (Reflection -> use this for 1.8 - 1.12)
# - RTag (Url: https://github.com/saicone/rtag) require to be installed! use this for Mojang mapping servers or if madeIn has problems on your server
# - NBTAPI (Url: https://www.spigotmc.org/resources/nbt-api.7939/) popular minecraft nbt api, need installation! (Or if any plugins shaded the nbtAPI, does not require!)
NBTSystem: spigot

# Available Economy systems:
# - Vault
# - TokenManager
Economy:
  enabled: false
  type: vault

#this repeater task checks players inventory every several times
#if menuMine items is moved in inventory, this will be fix it
#Note: this task can reduce server optimizations!
MenuItemCheckerTask:
  enabled: true
  #time per seconds
  time: 60