version: "1.7"

defaultLanguage: 'en'
logEnableMessages: true
Metrics: true
# Interact event used as in game menu creation system + set placeholders when someone opens the menu
# - if you don't want to use in game menu system & optimize disable this future
# - if you don't want to use placeholders disable it (it's also optimize the plugin)
InteractEvent: true
PlaceholderAPI_support: true

# Available NBT systems:
# - madeIn (Reflection)
# - RTag (Url: https://github.com/saicone/rtag) require to be install! use this for mojang mapping servers or if madeIn has problems on your server
# - NBTAPI (Url: https://www.spigotmc.org/resources/nbt-api.7939/) popular minecraft nbt api, need installation! (Or if any plugins shaded the nbtAPI, does not require!)
NBTSystem: madeIn

# Available Economy systems:
# - Vault
# - TokenManager
Economy:
  enabled: false
  type: vault

#this repeater task checks players inventory every several times
#if menuMine items is moved in inventory, this will be fix it
#Note: this task can reduce server optimizations!
MenuItemCheckerTask:
  enabled: true
  #time per seconds
  time: 60