version: "1.6"
# set it to none if you don't want to play any sounds!
MenuOpenSound: ITEM_CROSSBOW_HIT

defaultLanguage: 'en'
logEnableMessages: true
Metrics: true
# Interact event used as in game menu creation system + set placeholders when someone opens the menu
# - if you don't want to use in game menu system & optimize disable this future
# - if you don't want to use placeholders disable it (it's also optimize the plugin)
InteractEvent: true
PlaceholderAPI_support: true

Economy:
  enabled: false
  type: vault

#this repeater task checks players inventory every several times
#if menuMine items is moved in inventory, this will be fix it
#Note: this task can reduce server optimizations!
MenuItemCheckerTask:
  enabled: true
  #time per seconds
  time: 60