name: MenuMine
version: '0.6.2'
main: me.ehsanmna.menumine.MenuMine
api-version: 1.13
authors: [ EhsanMNA ]
softdepend: [PlaceholderAPI]
commands:
  menu:
    description: "Open menu - or change setting"
