name: MenuMine
version: '0.7.1'
main: me.ehsanmna.menumine.MenuMine
api-version: 1.13
authors: [ EhsanMNA ]
softdepend: [PlaceholderAPI,Vault]
commands:
  menu:
    description: "Open menu - or change setting"
