name: MenuMine
version: '1.0.0-Beta-3'
main: me.ehsanmna.menumine.MenuMine
api-version: 1.13
authors: [ EhsanMNA ]
softdepend: [PlaceholderAPI,Vault,TokenManager]
commands:
  menu:
    description: "Open menu - or change setting"
