package me.ehsanmna.menumine.models;

public enum Action {
    CONSOLE, COMMAND, MESSAGE, CLOSE, MENU, PERMISSION, CANCEL, GIVEMONEY, TAKEMONEY, HASMONEY, SOUND, TITLE, ACTIONBAR//, IF, ELSE,CHANGE
}
